name: CI/CD

on:
  pull_request:
    branches:
      - main
jobs:
  frontend-deploy:
    runs-on: ubuntu-latest
    steps:
      # SOURCE 단계 - 저장소 Checkout
      - name: Checkout-source code
        uses: actions/checkout@v3

      # Node version 확인
      - name: Check Node v
        run: node -v

      - name: Setup pnpm
        uses: pnpm/action-setup@v4.0.0
        with:
          version: 9

      - name: Install dependencies
        run: pnpm install

      # Application 빌드
      - name: Generate wbuild 
        run: pnpm build

      # docker image 빌드
      - name: Build docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/schedulehanaro .

      # docker hub 로그인
      - name: Login docker hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # docker hub 퍼블리시
      - name: Publish to docker hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/schedulehanaro

     # 5. SSH로 EC2에 접속하여 Application 실행
      - name: Connect to EC2 & Execute Application
        uses: appleboy/ssh-action@v1.0.0
        with:
          key: ${{ secrets.EC2_SSH_KEY }}
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          port: ${{ 22 }}
          script: |
            docker stop schedulehanaro
            docker rm schedulehanaro
            docker pull ${{ secrets.DOCKER_USERNAME }}/schedulehanaro
            docker run -d -p 80:80 --name schedulehanaro ${{ secrets.DOCKER_USERNAME }}/schedulehanaro
